// release/esbuild.config.mjs — Bundle the HOT-Step CPP server for portable distribution
//
// Usage: node release/esbuild.config.mjs
//
// Produces: release/staging/server/server.mjs
// - All TypeScript/JS source bundled into a single ESM file
// - better-sqlite3 marked external (native addon, can't be bundled)
// - ffmpeg-static excluded (replaced by config-based path resolution)
// - model-registry.json loaded via fs.readFileSync (not bundled inline)

import esbuild from 'esbuild';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

const result = await esbuild.build({
  entryPoints: [path.join(projectRoot, 'server/src/index.ts')],
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  outfile: path.join(projectRoot, 'release/staging/server/server.mjs'),

  // Native addon — can't be bundled into JS. Loaded from local node_modules/.
  external: ['better-sqlite3'],

  // ffmpeg-static is no longer imported directly — audioConvert.ts uses
  // getFFmpegPath() from config.ts which resolves the path at runtime.
  // But if any transitive dependency tries to import it, mark it external.
  // Also mark any other native/optional modules external.
  // Note: 'module' is a Node.js builtin but esbuild sometimes needs a hint.

  // Don't minify — keep readable for debugging production issues
  minify: false,
  sourcemap: false,

  // Tree-shake unused exports
  treeShaking: true,

  banner: {
    js: [
      '// HOT-Step CPP Server — bundled build',
      '// Generated by release/esbuild.config.mjs',
      '',
    ].join('\n'),
  },

  // Log build stats
  logLevel: 'info',
  metafile: true,
});

// Print bundle size summary
const outputs = result.metafile?.outputs || {};
for (const [file, info] of Object.entries(outputs)) {
  const sizeKB = (info.bytes / 1024).toFixed(1);
  console.log(`  ${file}: ${sizeKB} KB`);
}

console.log('\n✅ Server bundle complete');
